### ISSUE TITLE
Syntactically incorrect using directive breaks build

### ISSUE THREAD

**Issue by prolativ** [scalameta/metals#3961]
### Describe the bug

1. Create a file:
UnclosedLiteral.scala:
```scala
//> using scala 3.1.2

def foo[T] = ???
def bar = foo[""]
```

2. Run
```scala-cli setup-ide UnclosedLiteral.scala```

3. Open the project in VSCode

4. Metals' output:
```
2022.05.27 14:04:38 WARN  File watching failed, indexes will not be updated.
java.lang.NullPointerException
	at scala.meta.internal.mtags.CommonMtagsEnrichments$XtensionAbsolutePath.isSemanticdb(CommonMtagsEnrichments.scala:520)
	at scala.meta.internal.metals.MetalsLanguageServer.fileWatchFilter(MetalsLanguageServer.scala:1356)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$2(MetalsLanguageServer.scala:208)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$2$adapted(MetalsLanguageServer.scala:208)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$startWatch$2(FileWatcher.scala:144)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$startWatch$2$adapted(FileWatcher.scala:144)
	at scala.meta.internal.metals.watcher.FileWatcher$.hashFile(FileWatcher.scala:199)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$initFileTreeRepository$1(FileWatcher.scala:171)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$initFileTreeRepository$1$adapted(FileWatcher.scala:168)
	at com.swoval.files.Entries.get(Entries.java:27)
	at com.swoval.files.CachedDirectoryImpl.<init>(CachedDirectoryImpl.java:64)
	at com.swoval.files.CachedDirectoryImpl.<init>(CachedDirectoryImpl.java:76)
	at com.swoval.files.FileCacheDirectoryTree.newCachedDirectory(FileCacheDirectoryTree.java:629)
	at com.swoval.files.FileCacheDirectoryTree.register(FileCacheDirectoryTree.java:449)
	at com.swoval.files.FileCachePathWatcher.register(FileCachePathWatcher.java:24)
	at com.swoval.files.FileTreeRepositoryImpl.register(FileTreeRepositoryImpl.java:101)
	at scala.meta.internal.metals.watcher.FileWatcher$.$anonfun$startWatch$3(FileWatcher.scala:149)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at scala.meta.internal.metals.watcher.FileWatcher$.scala$meta$internal$metals$watcher$FileWatcher$$startWatch(FileWatcher.scala:147)
	at scala.meta.internal.metals.watcher.FileWatcher.restart(FileWatcher.scala:60)
	at scala.meta.internal.metals.Indexer.$anonfun$indexWorkspace$7(Indexer.scala:228)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.indexWorkspace(Indexer.scala:227)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$2(Indexer.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.meta.internal.metals.TimerProvider.timedThunk(TimerProvider.scala:25)
	at scala.meta.internal.metals.Indexer.$anonfun$profiledIndexWorkspace$1(Indexer.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Expected behavior

Metals should not crash and show an error about the incorrect using directive instead

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.5

### Extra context or search terms

scala-cli v0.1.6

**Comment by kpodsiad** [comment]
I dug a bit more into this issue to see if what is the real issue here. I started investigation on `0.11.5` and then I worked on `c517435d216113c366d118cf24375e9e61dbfa42` (it's a main without @dos65 fix). Issuse seems to be present only on `0.11.5`.

---

Let's start with what is causing NPE (God bless better NPE messages) - `java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.nio.file.Path.getFileName()" is null`. As we can see path is not a problem here, problem is caused by `getFileName`. But how did we get there?

In logs there is a message `ERROR Empty build targets. Expected at least one build target identifier.` - as it says there are no build targets so `collectPathsToWatch(buildTargets)` [here](https://github.com/scalameta/metals/blob/ce0fd5c8eef52106b996172094ea2a2abe381456/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L53-L61) will yield `PathsToWatch(files = Set(), directories = Set())`. Later, in [that code](https://github.com/scalameta/metals/blob/ce0fd5c8eef52106b996172094ea2a2abe381456/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L126-L154) `watchRoots` will be an list with one element - root path `List(/)`.

File watching will fail on path `/` as it's a valid path which doesn't have file name (or, according to docs, it'll return null if this path has zero elements) and that's exactly the path which is causing NPE in reported issue.

So I think that https://github.com/scalameta/metals/pull/3964 isn't fixing the reported problem, null guard checks wrong object, it should be path returned by `getFileName`, but is doesn't. matter because..


after https://github.com/scalameta/metals/pull/3758 and switching to `PathWatcher ` I think issue is no longer valid because it seems like [PathWatcher](https://github.com/swoval/swoval#pathwatcher) is watching only for files' events, not directory ones. I tried to reproduce issue in the same way, but there is no event with `/` path even though Metals' file watcher is registering the same watch root as before

---
That being said, I think https://github.com/scalameta/metals/pull/3964 can be safely reverted, bug was on Metals side but it was fixed (not on purpose, but it was).

**Comment by tanishiking** [comment]
@kpodsiad Thank you very much for investigating the root cause of the problem!


> watchRoots containing root path / means that Metals are observing everything. If there are many processes which are modifying files I can imagine that watching can cause increased CPU usage.

Indeed, with the latest nightly Metals, I received something below, which means Metals is actually watching all files under `/` (root directory). This should be fixed.
```
2022.05.31 15:56:58 ERROR Error encountered during file watching
java.nio.file.NoSuchFileException: /Users/tanishiking/.zsh_history.LOCK
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
```

---

Let me clarify something

- Metals 0.11.6 without https://github.com/scalameta/metals/pull/3964 should fix this NPE issue because switching to `PathWatcher` is watching only for files' events, not directory ones. Therefore, we can safely revert https://github.com/scalameta/metals/pull/3964 
- Metals watches `/` if `pathsToWatch` is `PathsToWatch(files = Set(), directories = Set())`, that should be fixed.
  - That problem (watching `/` problem) is distinct from this issue (NPE one)
  - Watching `/` problem had been the problem, and it is not caused by https://github.com/scalameta/metals/pull/3758, am I right?
- > Later, in [that code](https://github.com/scalameta/metals/blob/ce0fd5c8eef52106b996172094ea2a2abe381456/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L126-L154) watchRoots will be an list with one element - root path List(/).
  - I couldn't get it
    - For `PathsToWatch(files = Set(), directories = Set())`, `trie` should be `Leaf` (because of [this](https://github.com/scalameta/metals/blob/d0cf15ced536460bca4d8df5e16042a8595fd4d5/metals/src/main/scala/scala/meta/internal/metals/watcher/PathTrie.scala#L72))
    - and [watchRoots here](https://github.com/scalameta/metals/blob/d0cf15ced536460bca4d8df5e16042a8595fd4d5/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L141-L142) will be `Iterator('/')` because [Leaf.longestPrefix(fsRoot, ...) returns Iterator(fsRoot)](https://github.com/scalameta/metals/blob/d0cf15ced536460bca4d8df5e16042a8595fd4d5/metals/src/main/scala/scala/meta/internal/metals/watcher/PathTrie.scala#L34-L50)
    - So, you mean,  [watchRoots](https://github.com/scalameta/metals/blob/d0cf15ced536460bca4d8df5e16042a8595fd4d5/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L141-L142) will be `Iterator('/')` because `workspace.getRoot()` will be `/` under `ERROR Empty build targets. Expected at least one build target identifier` case?

**Comment by tanishiking** [comment]
If my assumptions are all correct, what we should do are

- (optional) revert https://github.com/scalameta/metals/pull/3964
- Open another issue for watching `/` directory problem.
  - It would be good to fix before `v0.11.6`, but we don't need to rush as it had been the issue for a long time (?)

**Comment by kpodsiad** [comment]
> * Metals 0.11.6 without [fix: prevent npe in filewatcher #3964](https://github.com/scalameta/metals/pull/3964) should fix this NPE issue because switching to `PathWatcher` is watching only for files' events, not directory ones. Therefore, we can safely revert [fix: prevent npe in filewatcher #3964](https://github.com/scalameta/metals/pull/3964)

It seems so. I tried to reproduce issue using the same steps but I couldn't. I logged incoming events and all of them were related to the files.

---

> Metals watches `/` if `pathsToWatch` is `PathsToWatch(files = Set(), directories = Set())`, that should be fixed.
> * That problem (watching `/` problem) is distinct from this issue (NPE one)
> * Watching `/` problem had been the problem, and it is not caused by [Reduce file watcher memory usage #3758](https://github.com/scalameta/metals/pull/3758), am I right?

1. Hard to say, at least not directly. Watching `/` is connected with with NPE, because code is calling `getFileName` which may return nullable String for root directory (and probably for other directories too), but after https://github.com/scalameta/metals/pull/3758 it isn't issue anymore. (Again, I'm saying this based on my observations)
2. Watching `/` had been a problem previously, before https://github.com/scalameta/metals/pull/3758.

---

> > Later, in [that code](https://github.com/scalameta/metals/blob/ce0fd5c8eef52106b996172094ea2a2abe381456/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L126-L154) watchRoots will be an list with one element - root path List(/).
> 
> * I couldn't get it
>   
>   * For `PathsToWatch(files = Set(), directories = Set())`, `trie` should be `Leaf` (because of [this](https://github.com/scalameta/metals/blob/d0cf15ced536460bca4d8df5e16042a8595fd4d5/metals/src/main/scala/scala/meta/internal/metals/watcher/PathTrie.scala#L72))
>   * and [watchRoots here](https://github.com/scalameta/metals/blob/d0cf15ced536460bca4d8df5e16042a8595fd4d5/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L141-L142) will be `Iterator('/')` because [Leaf.longestPrefix(fsRoot, ...) returns Iterator(fsRoot)](https://github.com/scalameta/metals/blob/d0cf15ced536460bca4d8df5e16042a8595fd4d5/metals/src/main/scala/scala/meta/internal/metals/watcher/PathTrie.scala#L34-L50)
>   * So, you mean,  [watchRoots](https://github.com/scalameta/metals/blob/d0cf15ced536460bca4d8df5e16042a8595fd4d5/metals/src/main/scala/scala/meta/internal/metals/watcher/FileWatcher.scala#L141-L142) will be `Iterator('/')` because `workspace.getRoot()` will be `/` under `ERROR Empty build targets. Expected at least one build target identifier` case?

It was late yesterday, I could change some details like swapping Iterator to List, but bottom line that for empty build targets I obtained empty `PathsToWatch` which resulted in registering watcher for `/`, just like you wrote under 3rd point.

I can double check this today's evening.

**Comment by dos65** [comment]
@kpodsiad thx for investigations!
I still don't fully understand how it was possible to get `/`  in `watchRoots` but overall looks like you are right

**Comment by tgodzik** [comment]
It would probably be good to default to current directory instead of `/` in case of empty build targets.
